name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-Java@v1
        with:
          java-version: 1.8

      - name: build project
        run:  chmod +x ./gradlew #./gradlew assemble

      #      - name: Build Release AAB
#        id: buildReleaseOne
#        run: chmod +x ./gradlew

      - name: Generate app APK.
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SSH_CONNECT }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}
          keyPassword: ${{ secrets.PASSWORD }}

#      - name: Upload AAB
#        id: uploadArtifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to play store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1.0.19
        with:
         serviceAccountJson: service_account.json
         packageName: com.ms.timerforedtl
         releaseFiles: app/build/outputs/bundle/release/app-release.aab
         track: alpha
         status: inProgress
         userFraction: 0.50
         whatsNewDirectory: app/whatsnew/





