name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-Java@v1
        with:
          java-version: 1.8
#      - name: Run test
#        run: chmod +x ./gradlew test

      - name: build project
        run:  chmod +x ./gradlew #./gradlew assemble




      - name: Build Release AAB
        id: buildRelease
        run: chmod +x ./gradlew

      - name: Generate app APK.
        id: buildRelease
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SSH_CONNECT }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}
          keyPassword: ${{ secrets.PASSWORD }}


      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.apk

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to play store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1.0.15
        with:
         serviceAccountJson: service_account.json
         packageName: com.ms.timerforedtl
         releaseFile: app/release/app-release.apk
         track: beta
         whatsNewDirectory: whatsnew/hope.txt
    #     mappingFile: app/build/outputs/mapping/release/mapping.txt
         inAppUpdatePriority: 5





