name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-Java@v1
        with:
          java-version: 1.8
#      - name: Run test
#        run: chmod +x ./gradlew test

      - name: build project
        run:  chmod +x ./gradlew #./gradlew assemble
      - name: Build Release AAB
        id: buildRelease
        run: chmod +x ./gradlew
#      - name: build release
#          run: ./gradlew bundleRelease
      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
#        uses: shahariar007/ssh_connect@ne/actions
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SSH_CONNECT }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}
          keyPassword: ${{ secrets.PASSWORD }}


