name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-Java@v1
        with:
          java-version: 1.8
      - name: Run test
        run: ./gradlew test

      - name: build project
        run: ./gradlew assemble

#      - name: build release
#          run: ./gradlew bundleRelease


